### ISSUE TITLE
Use of backspace to delete an entire line

### ISSUE THREAD

**Issue by excetara2** [twolfson/FindPlusPlus#17]
I use the package `ApplyFindResultsToBuffer` and find that deleting an entire line is not often the desired behavior so I have just changed the binding to `ctrl+backspace` and `ctrl+delete`. I was just curious what the rational was behind adding this as the default keybinding or it comes from notepad++?

**Comment by twolfson** [comment]
It's been 3.5 years since the initial writing so I have long forgotten the reasoning. I'm going to guess it was either Notepad++ or personal preference. Based on this TODO, it's possible that deleting a single line was a poor attempt at being able to delete an entire result

https://github.com/twolfson/FindPlusPlus/blob/0.4.2/FindPlusPlus.py#L16-L29
